### ISSUE TITLE
[FEATURE REQUEST] Make graph simple as possible

### ISSUE THREAD

**Issue by LdDl** [LdDl/osm2ch#10]
**Is your feature request related to a problem? Please describe.**
There are too many generated edges/vertices after parsing OSM (via edge expansion). Contraction hierarchies algorithm could take very much time to process all set of vertices. I'd suggest to implement [Edge contraction](https://en.wikipedia.org/wiki/Edge_contraction) to reduce size of graph for further contraction hierarchies algorithm

**Describe the solution you'd like and provide pseudocode examples if you can**
Find all vertices with degree == 2. Then recursively:
```
while exists vertex v with degree 2:
    - remove v and the 2 outgoing edges
    - add a new edge between the neighbours of v
    - the weight of the new edge is the sum of the weights of the deleted edg
```
reference - https://stackoverflow.com/questions/54954644/algorithm-to-simplify-reduce-graph

**Additional context**
* Would be cool to have an optional flag for CLI (for debugging purposes) also
* Some numbers for "before" and "after" (kinda benchmark) on specific graph

**Comment by LdDl** [comment]
Some kind of workaround could be found in https://github.com/LdDl/osm2ch/pull/12

**Comment by kkdd** [comment]
Hello,
OSM data has directed and undirected ways. So a simplifying pseudocode would be as follows:

```
while exists vertex v with undirected-degree 2:
    - remove v and the 2 edges
    - add a new undirected edge between the neighbors of v
    - the weight of the new edge is the sum of the weights of the deleted edges
while exists vertex v with inward-degree 1 and outward-degree 1:
    - remove v and the 2 edges
    - add a new directed edge between the neighbors of v
    - the weight of the new edge is the sum of the weights of the deleted edges
```
