### ISSUE TITLE
[BUG] Getting error while converting pbf to csv 

### ISSUE THREAD

**Issue by tamal-appsbee** [LdDl/osm2ch#4]
Getting following output

![image](https://user-images.githubusercontent.com/8500385/113586994-d5e1f100-964b-11eb-9099-1ea32786db8e.png)

**Comment by LdDl** [comment]
Hello @tamal-appsbee 

Output is saying that everything is fine actually (no "bad" restrictions)

**Comment by tamal-appsbee** [comment]
oh ok
Thanks you @LdDl

**Comment by LdDl** [comment]
There should be output file "map.csv" also :>
Closing.
